# syntax=docker/dockerfile:1.7

FROM node:20-alpine AS deps
WORKDIR /app

COPY package*.json ./
COPY apps/web/package*.json ./apps/web/
COPY packages/shared/package*.json ./packages/shared/
COPY packages/domain/package*.json ./packages/domain/
RUN npm install

FROM deps AS build
WORKDIR /app
COPY . .

ARG NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID=demo-mindsight
ARG NEXT_PUBLIC_FIREBASE_API_KEY=demo-api-key
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=demo-mindsight.firebaseapp.com
ARG NEXT_PUBLIC_FIREBASE_APP_ID=1:000000000000:web:0000000000000000000000
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=000000000000
ARG NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=localhost:9099
ARG NEXT_PUBLIC_AUTH_CONTINUE_BASE_URL=http://localhost:3000

ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
ENV NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
ENV NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
ENV NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=${NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST}
ENV NEXT_PUBLIC_AUTH_CONTINUE_BASE_URL=${NEXT_PUBLIC_AUTH_CONTINUE_BASE_URL}

RUN npm run build --workspace @mindsight/web

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/apps/web ./apps/web
COPY package*.json ./
COPY packages ./packages

ENV NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=demo-mindsight
ENV NEXT_PUBLIC_FIREBASE_API_KEY=demo-api-key
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=demo-mindsight.firebaseapp.com
ENV NEXT_PUBLIC_FIREBASE_APP_ID=1:000000000000:web:0000000000000000000000
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=000000000000
ENV NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=localhost:9099
ENV NEXT_PUBLIC_AUTH_CONTINUE_BASE_URL=http://localhost:3000

EXPOSE 3000
CMD ["npm", "run", "start", "--workspace", "@mindsight/web"]
