#!/usr/bin/env bash
set -euo pipefail

export NEXT_PUBLIC_API_BASE_URL="${NEXT_PUBLIC_API_BASE_URL:-http://127.0.0.1:8000}"
USE_FIREBASE_AUTH_EMULATOR="${USE_FIREBASE_AUTH_EMULATOR:-false}"
use_emulator="$(printf "%s" "${USE_FIREBASE_AUTH_EMULATOR}" | tr "[:upper:]" "[:lower:]")"
if [[ "${use_emulator}" =~ ^(1|true|yes|y|on)$ ]]; then
  export NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST="${NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST:-127.0.0.1:9099}"
  export NEXT_PUBLIC_FIREBASE_PROJECT_ID="${NEXT_PUBLIC_FIREBASE_PROJECT_ID:-demo-mindsight}"
  export NEXT_PUBLIC_FIREBASE_API_KEY="${NEXT_PUBLIC_FIREBASE_API_KEY:-demo-api-key}"
  export NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:-demo-mindsight.firebaseapp.com}"
  export NEXT_PUBLIC_FIREBASE_APP_ID="${NEXT_PUBLIC_FIREBASE_APP_ID:-1:000000000000:web:0000000000000000000000}"
  export NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:-000000000000}"
else
  unset NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST
  : "${NEXT_PUBLIC_FIREBASE_PROJECT_ID:?NEXT_PUBLIC_FIREBASE_PROJECT_ID is required when USE_FIREBASE_AUTH_EMULATOR=false}"
  : "${NEXT_PUBLIC_FIREBASE_API_KEY:?NEXT_PUBLIC_FIREBASE_API_KEY is required when USE_FIREBASE_AUTH_EMULATOR=false}"
  : "${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:?NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN is required when USE_FIREBASE_AUTH_EMULATOR=false}"
  : "${NEXT_PUBLIC_FIREBASE_APP_ID:?NEXT_PUBLIC_FIREBASE_APP_ID is required when USE_FIREBASE_AUTH_EMULATOR=false}"
  : "${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:?NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID is required when USE_FIREBASE_AUTH_EMULATOR=false}"
fi
export NEXT_PUBLIC_AUTH_CONTINUE_BASE_URL="${NEXT_PUBLIC_AUTH_CONTINUE_BASE_URL:-http://127.0.0.1:${WEB_PORT:-3000}}"

npm run dev --workspace @mindsight/web -- --hostname "${WEB_HOST:-127.0.0.1}" --port "${WEB_PORT:-3000}"
